rewrite ^/origin/sausages$ $scheme://$http_host/destination/sausages redirect;
rewrite ^/origin/tiffin$ $scheme://$http_host/destination/tiffin redirect;
rewrite ^/origin/muffins$ $scheme://$http_host/destination/muffins redirect;
rewrite ^/origin/doughnuts$ $scheme://$http_host/destination/doughnuts redirect;
rewrite ^/origin/pickles$ $scheme://$http_host/destination/pickles redirect;
rewrite ^/origin/pasta$ $scheme://$http_host/destination/pasta redirect;
rewrite ^/origin/soup$ $scheme://$http_host/destination/soup redirect;
rewrite ^/origin/carrots$ $scheme://$http_host/destination/carrots redirect;
rewrite ^/origin/carrots$ $scheme://$http_host/destination/carrots redirect;
rewrite ^/origin/carrots$ $scheme://$http_host/destination/carrots redirect;
rewrite ^/origin/soup$ $scheme://$http_host/destination/soup redirect;
rewrite ^/cola$ $scheme://$http_host/beans redirect;
rewrite ^/origin/peas$ $scheme://$http_host/destination/peas redirect;
rewrite ^/origin/sausages$ $scheme://$http_host/sausages redirect;
rewrite ^/origin/pancakes$ $scheme://$http_host/sausages redirect;