location /beans { proxy_pass http://http-echo-server-1:5678; }
location /some/beans { proxy_pass http://http-echo-server-1:5678; }
location /means { proxy_pass http://http-echo-server-2:5678; }
location /heinz { proxy_pass http://http-echo-server-1:5678; }
