location /sausages { proxy_pass http://http-echo-server-1:5678; }
location /bacon { proxy_pass http://http-echo-server-2:5678; }
location /soup { proxy_pass http://http-echo-server-1:5678; }
location /pancakes { proxy_pass http://http-echo-server-2:5678; }
location /beans { proxy_pass http://http-echo-server-1:5678; }
location /eggs { proxy_pass http://http-echo-server-2:5678; }